export const projets = [
  {
    id: 1,
    titre: "Premiers pas Html",
    description: "Introduction au language Html.",
    categorie: "Open Classroom",
    tags: ["Html"],
    lien: "Pas de liens disponible",
    photo: "/public/assets/projets/RidingCities.png",
  },
  {
    id: 2,
    titre: "Agence de voyage Html Css",
    description: "Introduction au language Css.",
    categorie: "Open Classroom",
    tags: ["Html", "CSS3", "Git"],
    lien: "Pas de liens disponible",
    photo: "/public/assets/projets/Booki.png",
  },
  {
    id: 3,
    titre: "Site mobile animation Css",
    description: "Introduction au language de script SASS.",
    categorie: "Open Classroom",
    tags: ["CSS3", "Sass", "Git"],
    lien: "https://github.com/Nikorasu47/oh-my-food",
    photo: "/public/assets/projets/OhMyFood.png",
  },
  {
    id: 4,
    titre: "Premier pas Js",
    description: "Introduction au language Javascript.",
    categorie: "Open Classroom",
    tags: ["Html", "CSS3", "Js"],
    lien: "https://github.com/Nikorasu47/carroussel-sur-js",
    photo: "/public/assets/projets/PrintIt.png",
  },
  {
    id: 5,
    titre: "Page web dynamique Js",
    description: "Utilisation avancée du JavaScript.",
    categorie: "Open Classroom",
    tags: ["Html", "CSS3", "Js"],
    lien: "https://github.com/Nikorasu47/sophie",
    photo: "/public/assets/projets/SophieBluel.png",
  },
  {
    id: 6,
    titre: "Application immobiliére",
    description: "Introduction a la bibliotheque React.",
    categorie: "Open Classroom",
    tags: ["React", "CSS3", "Git"],
    lien: "https://github.com/Nikorasu47/React-app/tree/master",
    photo: "/public/assets/projets/Kasa.png",
  },
  {
    id: 7,
    titre: "Optimisation Referencement",
    description: "Introduction au référencement web.",
    categorie: "Open Classroom",
    tags: ["React", "CSS3", "Git"],
    lien: "https://github.com/Nikorasu47/NinaOptiSite",
    photo: "/public/assets/projets/NinaCarducci.png",
  },
  {
    id: 8,
    titre: "Debuggage site existant",
    description: "Introduction au débogage de site web.",
    categorie: "Open Classroom",
    tags: ["React", "CSS3", "Git"],
    lien: "https://github.com/Nikorasu47/724events",
    photo: "/public/assets/projets/724Event.png",
  },
  {
    id: 9,
    titre: "Implementation Front-end React",
    description:
      "Utilisation et validation des précédents concepts dans un projet React.",
    categorie: "Open Classroom",
    tags: ["React", "Js", "Git"],
    lien: "https://github.com/Nikorasu47/ArgentBank-Frontend",
    photo: "/public/assets/projets/ArgentBank.png",
  },
  {
    id: 10,
    titre: "Planification developpement d'un site",
    description:
      "Utilisation de different outils en ligne afin de préparer le développement d'un site.",
    categorie: "Open Classroom",
    tags: ["Notion", "Kanban", "Figma"],
    lien: "Pas de liens disponible",
    photo: "/public/assets/projets/Qwenta.png",
  },

  // ... autres projets
];
